# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.CharField(max_length=200, null=True)),
                ('user_to', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('nonce', models.CharField(max_length=200, null=True)),
                ('checksum', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('acction_pos', models.IntegerField(unique=True)),
            ],
        ),
    ]
